name: Build driver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: cd driver && make clean && make

    - name: Install
      run: sudo insmod driver/build/opentpu.ko
